accounts:
  - name: alice
    coins: ["2000000000umeme"]
  - name: bob
    coins: ["1000000000umeme"]
validator:
  name: alice
  staked: "100000000umeme"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5000000umeme"]
build:
  main: "cmd/memed"
